# Publishes GitHub & PyPi release on v{version} tags
name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Release Package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.7"

      - name: Install dependencies
        run: |
          pip install poetry
          poetry install --only main

      - name: Build and publish to PyPI
        run: |
          poetry build

          poetry config pypi-token.pypi ${{ secrets.POETRY_PYPI_TOKEN }}
          poetry publish

      - name: Create GitHub release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git_tag=${{ github.ref }}
          release_name=${git_tag:10}
          release_desc="Release $release_name"
          hub release create -a dist/* -m "$release_desc" "$release_name"
